version: "3.6"

services:
  nginx:
    command: ["nginx", "-c", "/nginx_conf/nginx.conf", "-g", "daemon off;"]
    container_name: docere_nginx
    env_file:
      - ../../.env
    image: nginx:1.19.6-alpine
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.conf:/nginx_conf/nginx.conf
      - ./nginx.server.conf:/etc/nginx/templates/default.conf.template
      - ./secrets:/var/www/secrets
      - ../../public:/var/www/html

  iiif:
    image: lorisimageserver/loris
    ports:
      - 5004
    restart: always
    volumes:
      - /data/docere/facsimiles:/opt/loris/tests/img

  api:
    build:
      context: ../../
      dockerfile: ./packages/api/Dockerfile
    command: ["node", "./packages/api"]
    container_name: docere_api
    env_file:
      - ../../.env
    ports:
      - 3000
    restart: always
    volumes:
      - ../../:/app
    working_dir: /app

  db:
    container_name: docere_db
    env_file:
      - ../../.env
    image: postgis/postgis:13-3.1-alpine
    ports:
      - 5432
    volumes:
      - db_testing:/var/lib/postgresql/data

  xml_file_server:
    command: ["npx", "@docere/xml-file-server"]
    environment:
      - DOCERE_XML_BASE_PATH=/xml
    expose:
      - 3003
    image: node:14-alpine
    restart: always
    volumes:
      - /data/docere/xml:/xml

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/elasticsearch/data01:/usr/share/elasticsearch/data
    ports:
      - 9200

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/elasticsearch/data02:/usr/share/elasticsearch/data

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/elasticsearch/data03:/usr/share/elasticsearch/data

  es04:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es04
    environment:
      - node.name=es04
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: /data/elasticsearch/data04
        target: /usr/share/elasticsearch/data

volumes:
  db_testing:
    driver: local
